// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/serverA.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HiReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiReq) Reset()         { *m = HiReq{} }
func (m *HiReq) String() string { return proto.CompactTextString(m) }
func (*HiReq) ProtoMessage()    {}
func (*HiReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_serverA_847fbf9f57e87b17, []int{0}
}
func (m *HiReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiReq.Unmarshal(m, b)
}
func (m *HiReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiReq.Marshal(b, m, deterministic)
}
func (dst *HiReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiReq.Merge(dst, src)
}
func (m *HiReq) XXX_Size() int {
	return xxx_messageInfo_HiReq.Size(m)
}
func (m *HiReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HiReq.DiscardUnknown(m)
}

var xxx_messageInfo_HiReq proto.InternalMessageInfo

func (m *HiReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HiResp struct {
	Echo                 string   `protobuf:"bytes,1,opt,name=echo,proto3" json:"echo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiResp) Reset()         { *m = HiResp{} }
func (m *HiResp) String() string { return proto.CompactTextString(m) }
func (*HiResp) ProtoMessage()    {}
func (*HiResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_serverA_847fbf9f57e87b17, []int{1}
}
func (m *HiResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiResp.Unmarshal(m, b)
}
func (m *HiResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiResp.Marshal(b, m, deterministic)
}
func (dst *HiResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiResp.Merge(dst, src)
}
func (m *HiResp) XXX_Size() int {
	return xxx_messageInfo_HiResp.Size(m)
}
func (m *HiResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HiResp.DiscardUnknown(m)
}

var xxx_messageInfo_HiResp proto.InternalMessageInfo

func (m *HiResp) GetEcho() string {
	if m != nil {
		return m.Echo
	}
	return ""
}

func init() {
	proto.RegisterType((*HiReq)(nil), "pb.HiReq")
	proto.RegisterType((*HiResp)(nil), "pb.HiResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerAClient is the client API for ServerA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerAClient interface {
	Hi(ctx context.Context, in *HiReq, opts ...grpc.CallOption) (*HiResp, error)
}

type serverAClient struct {
	cc *grpc.ClientConn
}

func NewServerAClient(cc *grpc.ClientConn) ServerAClient {
	return &serverAClient{cc}
}

func (c *serverAClient) Hi(ctx context.Context, in *HiReq, opts ...grpc.CallOption) (*HiResp, error) {
	out := new(HiResp)
	err := c.cc.Invoke(ctx, "/pb.ServerA/Hi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerAServer is the server API for ServerA service.
type ServerAServer interface {
	Hi(context.Context, *HiReq) (*HiResp, error)
}

func RegisterServerAServer(s *grpc.Server, srv ServerAServer) {
	s.RegisterService(&_ServerA_serviceDesc, srv)
}

func _ServerA_Hi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerAServer).Hi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServerA/Hi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerAServer).Hi(ctx, req.(*HiReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerA_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ServerA",
	HandlerType: (*ServerAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hi",
			Handler:    _ServerA_Hi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/serverA.proto",
}

func init() { proto.RegisterFile("pb/serverA.proto", fileDescriptor_serverA_847fbf9f57e87b17) }

var fileDescriptor_serverA_847fbf9f57e87b17 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x48, 0xd2, 0x2f,
	0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0x72, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x52, 0x92, 0xe6, 0x62, 0xf5, 0xc8, 0x0c, 0x4a, 0x2d, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc,
	0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x64, 0xb8, 0xd8, 0x40, 0x92,
	0xc5, 0x05, 0x20, 0xd9, 0xd4, 0xe4, 0x8c, 0x7c, 0x98, 0x2c, 0x88, 0x6d, 0xa4, 0xc6, 0xc5, 0x1e,
	0x0c, 0x31, 0x4f, 0x48, 0x9a, 0x8b, 0xc9, 0x23, 0x53, 0x88, 0x53, 0xaf, 0x20, 0x49, 0x0f, 0x6c,
	0x9a, 0x14, 0x17, 0x8c, 0x59, 0x5c, 0x90, 0xc4, 0x06, 0xb6, 0xcd, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x60, 0xf7, 0xe2, 0x97, 0x81, 0x00, 0x00, 0x00,
}
